name: Build Debian Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Package Directory
        run: make VERSION=${GITHUB_REF#refs/tags/v} build

      - name: Build .deb Package
        run: dpkg-deb --build build/

      - name: Release Package
        uses: softprops/action-gh-release@v2
        with:
          files: "build/*.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
